import { createClient } from '@supabase/supabase-js';
import { GoogleGenAI } from "@google/genai";
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
dotenv.config();

const apiKey = process.env.VITE_GEMINI_API_KEY!;
const supaUrl = process.env.VITE_SUPABASE_URL!;
const supaKey = process.env.VITE_SUPABASE_ANON_KEY!;

const supabase = createClient(supaUrl, supaKey);
const genAI = new GoogleGenAI({ apiKey });

async function sync() {
    console.log('--- GENERATING EMBEDDINGS SQL ---');

    const { data: products, error } = await supabase
        .from('products')
        .select('*')
        .is('embedding', null);

    if (error) {
        console.error('Fetch error:', error);
        return;
    }

    if (!products || products.length === 0) {
        console.log('No products to vectorize.');
        return;
    }

    console.log(`Vectorizing ${products.length} products...`);
    let sql = '-- Vector updates generated by sync_vectors\n\n';

    for (const p of products) {
        const textToEmbed = `${p.name} ${p.description || ''} ${p.cbd_percentage ? 'CBD ' + p.cbd_percentage + '%' : ''} ${(p.attributes?.benefits || []).join(' ')}`;

        try {
            const response = await genAI.models.embedContent({
                model: "gemini-embedding-001",
                contents: [{ parts: [{ text: textToEmbed }] }]
            });

            let embedding = response.embeddings?.[0]?.values || [];
            if (embedding.length > 768) embedding = embedding.slice(0, 768);

            if (embedding.length === 768) {
                sql += `UPDATE products SET embedding = '${JSON.stringify(embedding)}'::vector WHERE id = '${p.id}';\n`;
                console.log(`✅ Vectorized: ${p.name}`);
            }
        } catch (e) {
            console.error(`❌ Failed: ${p.name}`, e);
        }
        await new Promise(r => setTimeout(r, 200));
    }

    const outputPath = 'supabase/apply_vectors.sql';
    fs.writeFileSync(outputPath, sql);
    console.log(`\n--- FINISHED ---`);
    console.log(`SQL file created at: ${outputPath}`);
    console.log(`PLEASE RUN THE CONTENT OF THIS FILE IN YOUR SUPABASE SQL EDITOR.`);
}

sync();
